//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Desencriptar_SR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Desencriptar_SR.Idesencriptar")]
    public interface Idesencriptar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Idesencriptar/desencript", ReplyAction="http://tempuri.org/Idesencriptar/desencriptResponse")]
        string desencript(string sCadena, byte[] bEncript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Idesencriptar/desencript", ReplyAction="http://tempuri.org/Idesencriptar/desencriptResponse")]
        System.Threading.Tasks.Task<string> desencriptAsync(string sCadena, byte[] bEncript);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdesencriptarChannel : BLL.Desencriptar_SR.Idesencriptar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdesencriptarClient : System.ServiceModel.ClientBase<BLL.Desencriptar_SR.Idesencriptar>, BLL.Desencriptar_SR.Idesencriptar {
        
        public IdesencriptarClient() {
        }
        
        public IdesencriptarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdesencriptarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdesencriptarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdesencriptarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string desencript(string sCadena, byte[] bEncript) {
            return base.Channel.desencript(sCadena, bEncript);
        }
        
        public System.Threading.Tasks.Task<string> desencriptAsync(string sCadena, byte[] bEncript) {
            return base.Channel.desencriptAsync(sCadena, bEncript);
        }
    }
}
