//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Encriptar_SR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Encriptar_SR.Iencriptar")]
    public interface Iencriptar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iencriptar/Encript", ReplyAction="http://tempuri.org/Iencriptar/EncriptResponse")]
        string Encript(string sCadena, byte[] bEncript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iencriptar/Encript", ReplyAction="http://tempuri.org/Iencriptar/EncriptResponse")]
        System.Threading.Tasks.Task<string> EncriptAsync(string sCadena, byte[] bEncript);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IencriptarChannel : BLL.Encriptar_SR.Iencriptar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IencriptarClient : System.ServiceModel.ClientBase<BLL.Encriptar_SR.Iencriptar>, BLL.Encriptar_SR.Iencriptar {
        
        public IencriptarClient() {
        }
        
        public IencriptarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IencriptarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IencriptarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IencriptarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Encript(string sCadena, byte[] bEncript) {
            return base.Channel.Encript(sCadena, bEncript);
        }
        
        public System.Threading.Tasks.Task<string> EncriptAsync(string sCadena, byte[] bEncript) {
            return base.Channel.EncriptAsync(sCadena, bEncript);
        }
    }
}
