//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.SVC_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC_service.Iservice")]
    public interface Iservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Calculador", ReplyAction="http://tempuri.org/Iservice/CalculadorResponse")]
        string Calculador(int idigito1, int idigito2, char cSimbolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Calculador", ReplyAction="http://tempuri.org/Iservice/CalculadorResponse")]
        System.Threading.Tasks.Task<string> CalculadorAsync(int idigito1, int idigito2, char cSimbolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Palindromo", ReplyAction="http://tempuri.org/Iservice/PalindromoResponse")]
        bool Palindromo(string sPalabra, bool bPalin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice/Palindromo", ReplyAction="http://tempuri.org/Iservice/PalindromoResponse")]
        System.Threading.Tasks.Task<bool> PalindromoAsync(string sPalabra, bool bPalin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IserviceChannel : UI.SVC_service.Iservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IserviceClient : System.ServiceModel.ClientBase<UI.SVC_service.Iservice>, UI.SVC_service.Iservice {
        
        public IserviceClient() {
        }
        
        public IserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Calculador(int idigito1, int idigito2, char cSimbolo) {
            return base.Channel.Calculador(idigito1, idigito2, cSimbolo);
        }
        
        public System.Threading.Tasks.Task<string> CalculadorAsync(int idigito1, int idigito2, char cSimbolo) {
            return base.Channel.CalculadorAsync(idigito1, idigito2, cSimbolo);
        }
        
        public bool Palindromo(string sPalabra, bool bPalin) {
            return base.Channel.Palindromo(sPalabra, bPalin);
        }
        
        public System.Threading.Tasks.Task<bool> PalindromoAsync(string sPalabra, bool bPalin) {
            return base.Channel.PalindromoAsync(sPalabra, bPalin);
        }
    }
}
