//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Fibonacci_SR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Fibonacci_SR.Ifibonacci")]
    public interface Ifibonacci {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifibonacci/Fibo", ReplyAction="http://tempuri.org/Ifibonacci/FiboResponse")]
        string Fibo(int iLimite, string sResultadof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifibonacci/Fibo", ReplyAction="http://tempuri.org/Ifibonacci/FiboResponse")]
        System.Threading.Tasks.Task<string> FiboAsync(int iLimite, string sResultadof);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IfibonacciChannel : BLL.Fibonacci_SR.Ifibonacci, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IfibonacciClient : System.ServiceModel.ClientBase<BLL.Fibonacci_SR.Ifibonacci>, BLL.Fibonacci_SR.Ifibonacci {
        
        public IfibonacciClient() {
        }
        
        public IfibonacciClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IfibonacciClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfibonacciClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfibonacciClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Fibo(int iLimite, string sResultadof) {
            return base.Channel.Fibo(iLimite, sResultadof);
        }
        
        public System.Threading.Tasks.Task<string> FiboAsync(int iLimite, string sResultadof) {
            return base.Channel.FiboAsync(iLimite, sResultadof);
        }
    }
}
